server:
  port: ${APP_PORT}
  servlet:
    context-path: /
spring:
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  application:
    name: PaydaiServerApplication
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt_secret:
      key: ${JWT_SECRET}
  server:
    url: ${BASE_URL}
  stripe:
    secret_key: ${STRIPE_SECRET_KEY}
    base_url: ${STRIPE_BASE_API}
  paydai:
    client_callback: ${PAYDAI_RETURN_CALLBACK_URL}