server:
  port: ${APP_PORT?:8000}
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  application:
    name: PaydaiServerApplication
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
application:
  server:
    url: ${BASE_URL}