server:
  port: ${APP_PORT}
  servlet:
    context-path: /
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256
          audiences: https://api-paydai
          issuer-uri: https://dev-jb52jse3wmo5txth.us.auth0.com
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  application:
    name: PaydaiServerApplication
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  server:
    url: ${BASE_URL}
  stripe:
    secret_key: ${STRIPE_SECRET_KEY}