server:
  port: ${APP_PORT}
  servlet:
    context-path: /
spring:
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  application:
    name: PaydaiServerApplication
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.springframework.orm.jpa.vendor.SpringJtaPlatform
        format-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt_secret:
      key: ${JWT_SECRET}
  server:
    url: ${BASE_URL}
  stripe:
    secret_key: ${STRIPE_SECRET_KEY}
    base_url: ${STRIPE_BASE_API}
    webhook:
      secret:
        balance: ${STRIPE_WEBHOOK_SECRET_BALANCE}
        transfer: ${STRIPE_WEBHOOK_SECRET_TRANSFER}
        invoice_connect: ${STRIPE_WEBHOOK_SECRET_INVOICE_CONNECT}
  paydai:
    stripe_acct: ${PLATFORM_ACCT}
    client_callback: ${PAYDAI_RETURN_CALLBACK_URL}